// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ArchiverClient is the client API for Archiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArchiverClient interface {
	CreateArchiveRequest(ctx context.Context, in *CreateArchiveRequestRequest, opts ...grpc.CallOption) (*CreateArchiveRequestResponse, error)
	ListArchiveRequestsForUser(ctx context.Context, in *ListArchiveRequestsForUserRequest, opts ...grpc.CallOption) (*ListArchiveRequestsForUserResponse, error)
}

type archiverClient struct {
	cc grpc.ClientConnInterface
}

func NewArchiverClient(cc grpc.ClientConnInterface) ArchiverClient {
	return &archiverClient{cc}
}

func (c *archiverClient) CreateArchiveRequest(ctx context.Context, in *CreateArchiveRequestRequest, opts ...grpc.CallOption) (*CreateArchiveRequestResponse, error) {
	out := new(CreateArchiveRequestResponse)
	err := c.cc.Invoke(ctx, "/Archiver/CreateArchiveRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *archiverClient) ListArchiveRequestsForUser(ctx context.Context, in *ListArchiveRequestsForUserRequest, opts ...grpc.CallOption) (*ListArchiveRequestsForUserResponse, error) {
	out := new(ListArchiveRequestsForUserResponse)
	err := c.cc.Invoke(ctx, "/Archiver/ListArchiveRequestsForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArchiverServer is the server API for Archiver service.
// All implementations must embed UnimplementedArchiverServer
// for forward compatibility
type ArchiverServer interface {
	CreateArchiveRequest(context.Context, *CreateArchiveRequestRequest) (*CreateArchiveRequestResponse, error)
	ListArchiveRequestsForUser(context.Context, *ListArchiveRequestsForUserRequest) (*ListArchiveRequestsForUserResponse, error)
	mustEmbedUnimplementedArchiverServer()
}

// UnimplementedArchiverServer must be embedded to have forward compatible implementations.
type UnimplementedArchiverServer struct {
}

func (UnimplementedArchiverServer) CreateArchiveRequest(context.Context, *CreateArchiveRequestRequest) (*CreateArchiveRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateArchiveRequest not implemented")
}
func (UnimplementedArchiverServer) ListArchiveRequestsForUser(context.Context, *ListArchiveRequestsForUserRequest) (*ListArchiveRequestsForUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArchiveRequestsForUser not implemented")
}
func (UnimplementedArchiverServer) mustEmbedUnimplementedArchiverServer() {}

// UnsafeArchiverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArchiverServer will
// result in compilation errors.
type UnsafeArchiverServer interface {
	mustEmbedUnimplementedArchiverServer()
}

func RegisterArchiverServer(s grpc.ServiceRegistrar, srv ArchiverServer) {
	s.RegisterService(&Archiver_ServiceDesc, srv)
}

func _Archiver_CreateArchiveRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArchiveRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiverServer).CreateArchiveRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Archiver/CreateArchiveRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiverServer).CreateArchiveRequest(ctx, req.(*CreateArchiveRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Archiver_ListArchiveRequestsForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArchiveRequestsForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiverServer).ListArchiveRequestsForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Archiver/ListArchiveRequestsForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiverServer).ListArchiveRequestsForUser(ctx, req.(*ListArchiveRequestsForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Archiver_ServiceDesc is the grpc.ServiceDesc for Archiver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Archiver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Archiver",
	HandlerType: (*ArchiverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateArchiveRequest",
			Handler:    _Archiver_CreateArchiveRequest_Handler,
		},
		{
			MethodName: "ListArchiveRequestsForUser",
			Handler:    _Archiver_ListArchiveRequestsForUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "archiver.proto",
}
